// <auto-generated />
#nullable enable

using System;

namespace {{namespace_name}};

public partial class {{class_name}}
{
    public void HelloThere()
    {
        Console.WriteLine("Hello there from {{class_name}}!");
    }
}