// <auto-generated />
#nullable enable

using System;

namespace Packaging.Generators;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public class HelloThereAttribute : Attribute
{	
	public HelloThereAttribute()
	{
	}
}