version: '3.4'

# Docker Compose with database support
# It will create all needed development database container and setup all needed stuff like ports, volumes etc.
#
# Be sure you have installed:
# - Docker Desktop
# - MongoDB Compass
# 
# Starting the compose (run command from the repository root):
# docker-compose -p "orleans_storage_mongo_repository" -f docker-compose-infrastructure.yml up -d
#
# NOTE:
# This docker compose will mount mongo db data to the '_db/mongo' folder.
# With time I can grow to a big size, so you can delete it from time to time.
services:

  # MONGODB: Open Source MongoDb for development (If you are running multiple MongoDB containers, change the port as I changed here to 27018)
  research.mongodb:
    image: mongo:latest
    container_name: 'research.mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_CONNECTION_STRING: mongodb://dev:dev@localhost:27019
    restart: always
    ports:
      - '27019:27017'

    # Defining the 'volumes' where we can specify the physical locations. 
    # Here first part './mongo/data' is the folder from your current location of the 
    # 'docker.compose.yml' and the second part '/data/db' is the default folder 
    # location of the 'mongo' docker image.
    volumes:
      - ./_db/mongo:/data/db
      - ./_db/mongo/configdb:/data/configdb
